spring.application.name=crudbasico1
spring.datasource.url=jdbc:postgresql://localhost:5432/crudbasico1
spring.datasource.username=postgres
spring.datasource.password=1970
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#No envia todo el trace al usuario
server.error.include-stacktrace=never

